---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/srobroek/flux-home
---
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - ./apps/kustomization.yaml

