---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vars
  namespace: flux-system
spec:
  interval: 10m0s
  # dependsOn:
  #   - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/k8s-home/vars/
  prune: true
  wait: true
  timeout: 5m0s
