---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: external-secrets
spec:

  interval: 15m
  chart:
    spec:
      chart: connect
      version: '1.10.0'
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: external-secrets
  values:
    connect: 
      credentials:
        valueFrom:
          secretKeyRef:
            name: onepassword-connect-secret
            key: 1password-credentials.json

