apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:uO3lRUTPXX+Dk8znYywImkqAurv9vGoWJuSbi8+/LROnpaSi3WfkjYQlLhn7TcDioRQbYmpns0ackbqwvPe3S5Mhkp87V7XCF5ZAdIiSqO2MbAGdMsSF3katD0nsKLhZb942BznrRlNXAGaiwx3/3Zk/yIwZT3MQ1Hg0zsxgDTt7W3u99HoTUWuy7b0Iik5A7OSNr4apZj9fHwN9Ww7r6+NCSJiXtfpdAlpl5HuGdr2i4A5inVyUZEt/vJ55dMqLa+wuL6LhRM5MQNsFVSAbqrbRbb/fGeJGtEnN2EAuET+dBxP5LgOXuOnOr8SKyjbH9K2fMI7OFpoRAzmo3g775A6XSDPSaiRwlno6gRne49K8eJB9QVvZ1+BQ1AyCUWoZL58A3kpepeW1o5EsNM21fZIBhYwrfchhoLa60aW44H7apQDV9IJhBkI1V0Sfx1uTyFWckpGy9jbM8yog90z//sU3POObYLo1GFNSyx02wXWWwBvB9GC/8XvW7xpQ0f9CneFmU6wC6RvrUEVhc5EYPWx3Gs6lV1lHLFh60TVtt4VVosPwUQehpehyryAVbgRR5C6rQVqMDE0aSuL/uc4R/lDRcWleLBut9wSNPNTCrpsAWOCVrYWLx0N9PI2a3kPll8+xsY8QfT+yJkAs2xEeJrbGArFUxG0VT63zmRNS79zGExEdSW00RJfAjm1GtTbSQVZ3rQt0JPpawWSHzSfgNYo8GY8yoWOOgYJNGzXfhcIA1GIskN7eyKUlQVxsQQ9SDPQnHAJT0jnpJp9axWuL2/t/NFe345dw/BgJtSGw1SGbP+LWknw8nJ01J8t5VrZINKt5++3p7DDCVOdwUblUNMSCFoTBEL9Gl5LsbMlBAn3FaOso8DdrN48bEvw0zrnuClz88q2VoUpOBEFgiKe9njJODu2hvanCTmdYCqkX6ePTVqFWvfdDprf5OtxIs3jL8Po+MY1SC9nLjAYHEkqr0PW4I0S9jROg3d2gUaNWhQu2DBrX6HOuy+hc9y8/hNfarWeav2yMjIS1pDotLPIxZqYjiXMDjozAEVNQ77Jn5AEn9hyeAQIRXHjtnZfGWD1W/XI8WIu/h56ujNtTwWLNK7NJLHK+ekFeAWj3wrYnIMVw82qogWaiSqhOh28P5auLzcdmsjyXdhg/PIGw2rvxkVa8UNEtOmHZLRlj1EpSJLrdbRtmCJW9rg1lDFXmET6iFvZEWDYb0V2m6RufsO6QADxgaDLzXeFoEkuFFLNh0y8RzZ8Ace6/IVxxKWZ9czjSPQJfzm22EB1huw7XjQLXdjJAyg1NWTv/5FDeswOkjONteB+TxPa9LXSBme/7MCVUIe+aE05Ort4/LIqCCE18aqYNKXpS2jP6IhvPofpnNanhlw5NhJOjUhMHOjYcxHAOHu5yQjXP1AzTZo+ICPiDiYUs85I=,iv:Zt4tY+sN+S8FNGDd6n09ZNjotCCrVogU68JFcfkX2tg=,tag:Qa+lLAs3a088elWVpVPPTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxf90r5vuaxapj7alklj2mt3udksq873j0vcmgchz9e4y3jmpefqtx6alq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQUNlc0cyKzJvWUNMMTFX
            Y0JZTklRRVp4TUpuSlRIaWd6Y29WYWIwM3c4CjdQTVNXbXZPSmdKd2lVZGQxQ2xR
            TFFjL3VTM0ovZmFHM0NHK0pxU250cnMKLS0tIElUdlpuSGpsYmowNUVpSElhUmo4
            R0Q1T1d1cnErTktWYnpJbXg1TDl3UzAK+r/J8VMe6HdL7WLKyUrjNltXfL6Eh0GS
            bceRr0BOpCt/rRp07HN4RmNoYF3eImiEDKl44AAs5nEDjJgg+Ww7jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-21T09:19:18Z"
    mac: ENC[AES256_GCM,data:jAu5K2l5QtPyOUOpmDl+22a/+Pz2nMOFcWpKGhTWPHjBB1TNTZe5gcBawYKjdioRvt/ZRz/CzvZayGWzTgk1pKAqtR8o0JnMv5/tvFZdOSYcTjw4lLsBM8Flx5p12R8rQ+bNe/OnW0WXlZxue2zjdQPO5WcPWvsrc2sJF8GNKQ0=,iv:Bu9vuchpPDnF/j/PDDlEhduSMAueQrXEiXh8USV+0cY=,tag:4p+0JmtqpgnaeC93n5t8hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
