apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:1mp605uaAtBDYHQLHCqGTdaf+ozVe6RacI9zPyDVK6dpwXYRr3Y+CQMHqPZqmRQltvEb18WFMmoD8RUZosPMgoY2KNWa9fdhOqsit2ZO3XSwly01qIgIHKTLFPNO950l8XrRrRY08wQUyXbZtjUUfcqUiJkUXLzXdtwA+EeWly/uWKhH8QMzDNIqxNA+z/LPHEh6kJ2nT1kjm8fRstIvDHr5bJ9hodDu0pGdEQL24KiH/ZJ+PpJRbZ2EWG3X5aRwsnaOLPNQIdUi1k0b1uwA8oMCcu3aLzr7zEiIg5sZMLNXTZVZEh/eaKhMu26C8+kig7kSjQJTBfQBAjBhUYvL7LYdGpJhZakEwDRKFVgcPNgWVYnzlAOJmlJnAroRE5O4/zfyGWwJ2pj/aM9LK2fe7Vk+vQocJIkpLr4/Qjv0ooZjkSlYosDSKnDoXZydlZi6HDtA5FMbC/6QoOIElW/TdAvCWbakGN8NHoTEs6eiIswo6+35AZYF+zVDk0YQAzhP2cV9YJrgR7ryHL7xEqxjPZbjNudi6sHHMOhFjDPtGTNRaverv91E4npTB9IOtYdGTHyddv+rjXSyklHjaKSgu1Nv7i635JZlKfiM8+fu6isZ9jPjU/Chx+xhsUEdh285vIx3NOvfPYWNTAXZ90eWuLk7uurna65o0v5fYOIGNqQUMpo1UlVIMEk1Jh99MQYdrubEjigycPxo3//MFyQdRA+ET5HIKyUeYbhkbh5zJ5bg0J8fz6u23oE5aZ7PIf9/Ld0sjiX8+DkgRKtXpjueX3FCGd0gMQBDewvVtmqvTDwmJu0+ooHcMc9VRMzyMVJU2OcW0+SW63BpKC1GLqsf/t/rj3K2+yFzoQEi4rXMBjvsl73qMGzMiumY0FMw4jvaAX8j70rKuGBqZFTXciZm9MhP/IDERc9iangBzumuvbUM5OLDErmq7uoBogvR8fK+sAecRLSLhaZMW5jbPjXotITJNIwF1QUy7++rgToS2RVDjAbef6IjxrROiJI7IKAwObw0/QU571Bg/TQQzJH/zMqhswVAU54M6k5DO2Sm3RA3Nx4oE+kkmbs1e581ov6UF/N1l/WYzFNhVYyGhtuU59pJyM+BsEdblM0XuVV5VT99ZLAcLYLfNwcXUicW7KyY9BQ1nPf4UZAsdgD7wfam+r9ZEOtxgiTfGdDgoye7LxpD4q2bcOm4aTmrMEoOYYqUSAgF6KMsTXqteLbpmzc00X68aDErSawBRIUCD0mc432rSjqhdUjlSweagXZ89bL9mPuIgBU2kOxoFUXBw4FzHOmQR0mB7mmCJLfrTMnSs1JTKbaSNPgMO7/vl4R9StAcl2zeVFMLUrZLPkQkaNQvXtMYcDAY4H/fCHxN4AZpQtfAVaGZm2yhCA59LMXQe4zuM+ABt7w9wZXHypRd1M8Ifv2Kup22dh0=,iv:6IvUON+dV6GDKlphmLxAyzj5iubSLm4o1ImJbu3z4TQ=,tag:YHClDzbwZvL7+jqs1rPV7Q==,type:str]
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:PNMQLy8nwUEQAPMK80n60vWAvnIZbeAfxA0Y1XhfsZVK+e14JZ1Mg+GMI3YbxpffgbrEoS3Uz88aa7CJ6sl4DBmpaOV66Jem7GHUd+qFLiWXOh3YL2AGDkRQE3jrvojkknunoMXtwfVX33w7j76tW8k6JkV+Ewfx40yS0Dh7KvJh+w0Mx9mankq12Jl+v+L2WQpDVbUeshznVTwUSnJrZIjipT9vUsySugTfX2w7pyJBcHeETBysY+IW4K8ZKMZ0HhNAF7pjyAdhLkx4I2UpWdsCeJcqmofFmNRI0RbFsKOSFucZiUnuYi1igen2SkOjrpHgxNCJDDYN4KhvshKYrxAAorucd1FwQkNeWA73sxsO95BfDHiJ8BxHbpBYjmrdRD1/cW1RFnyi/gRmvPWclBxMUFA6+nAYzsksHk7pYM2zA3cOS8bqgzWgHUjVn8jLSy0aNdtIsBRqGsqguuZo4DOK1RjhUIX2A85yizxM4gerCrd6fQbEgNPvIFFVUku0egqudMh/ezfM3af9UbsaOi0LCAtpE2gicZXGNZNOJbSxDZ0NBAX40qFRnh2Typ9WwTJV/OXDZGDR0LWAgN8FvlpZihNdZOvj2ZIfTqb/EI/DPjiWWEr2lw4BH617gWQZpm692t4Qb2QVcIWir54V4a5nj+rcqA2KLmZZ3tjtc3Ve4DwZ1f9ou/TxX+w8IBWoCeXB18OJCZLyWNd6k2QbzY8benLUnmiwmOH+b4I=,iv:WYo+B6wZY+a/upjrDILt/xRq0w9UmBR0Ru4OMzGpkGI=,tag:5PlDUHiw4Cohe2odA9ZvuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxf90r5vuaxapj7alklj2mt3udksq873j0vcmgchz9e4y3jmpefqtx6alq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UkYraWhwK2JVY3ZHdFlh
            ODVyMkRjSnZjbUxmNDBtMGFVZTNod1FxeUVBCnVvR3JCeGRSQWpIeXhOR01iSUN4
            MTJZcXBtTjZNa0hhUHhMWm1EQ0JXekkKLS0tIEMwYncvcmYzV1FGUGFKYUhxY0xs
            cVp5UkVHcXAxZFlrbjI4c1poVHdvUU0KreqzA80QWsas+XTesk2oCtPSwULPqfI8
            1f1YqUKRdMZ84ww/Cz46UCFx59Wn5Nw/ZQItwgGiiJ9akyCjhJM8Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-21T09:40:58Z"
    mac: ENC[AES256_GCM,data:RyvPGdF8argr9VAhMBHGSFw+TDnHiGQ5mCT1cH5rNirVkbqtimCVsUFChxmezwr6B2Cg0Xwlv5WOvNj79igRVblcCCNvvscYGabaET96/OxmMnUiLKoIx9ncRFaCtJ3U7DM+j+FY9GIiK8vMFnlTr80vajnyYdcXcFUiL5V7qcg=,iv:XbxMGs67xuT+WKszkq8BluimxO3o14mGeCZHe6XPPpo=,tag:MHrJUIfNRr7rSj2Uhk8/gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
