---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./apps/external-secrets/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-apps
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
  interval: 30m
  retryInterval: 1m
  timeout: 3m