---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-proxy
spec:

  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 'v2.9.6'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ports:
      web:
        redirectTo: websecure
    certResolvers:
      letsencrypt: ß
    env:
      - name: CF_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            key: apiToken
            name: cloudflare-api-credentials
    persistence:
      enabled: true
      name: data
      accessMode: ReadWriteOnce
      size: 128Miß
      storageClass: "nfs-standard"
      path: /data
      annotations: {}
