---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-traefik-proxy
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./apps/traefik-proxy/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-apps
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: traefik-proxy
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: app-settings
        optional: true
      - kind: Secret
        name: app-secrets
        optional: true
---