---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik.yaml
  - csi-driver-nfs.yaml
  - bjw-s.yaml
  
  #- ./onepassword-connect.yaml

  # - ./actions-runner-controller.yaml
  # - ./backube.yaml
  # - ./bitnami.yaml

  # - ./calico.yaml
  # - ./cloudnative-pg.yaml

  # - ./descheduler.yaml
  # - ./dysnix.yaml
  # - ./emqx.yaml
  # - ./external-dns.yaml
  #- ./external-secrets.yaml
  # - ./grafana.yaml
  # - ./hajimari.yaml
  # - ./ingress-nginx.yaml
  # - ./jetstack.yaml
  # - ./kyverno.yaml
  # - ./metrics-server.yaml
  # - ./node-feature-discovery.yaml
  # - ./piraeus.yaml
  # - ./prometheus-community.yaml
  # - ./rook-ceph.yaml
  # - ./stakater.yaml
  # - ./tf-controller.yaml
  # - ./weave-gitops.yaml